export const questions = [
    {
        query: "Who was the last emperor to rule a united Roman Empire?",
        answerA: "Caligula",
        answerB: "Nero",
        answerC: "Marcus Aurelius",
        answerD: "Theodosius I",
        correct: "D",
    },
    {
        query: "What is the name of the second-largest desert in Africa?",
        answerA: "Sahara",
        answerB: "Namib",
        answerC: "Kalahari",
        answerD: "Great Victoria",
        correct: "C",
    },
    {
        query: "Who won the 1997 Champions League final?",
        answerA: "Real Madrid",
        answerB: "AC Milan",
        answerC: "Juventus",
        answerD: "Borussia Dortmund",
        correct: "D",
    },
    {
        query: "In which year was JavaScript released?",
        answerA: "1986",
        answerB: "1995",
        answerC: "1999",
        answerD: "2006",
        correct: "B",
    },
    {
        query: "Who is the frontman of the legendary rock band The Who?",
        answerA: "Roger Daltrey",
        answerB: "Robert Plant",
        answerC: "Kurt Cobain",
        answerD: "Ozzy Osbourne",
        correct: "A",
    },
];
